### ISSUE TITLE
Setuping Redis connection during initialization

### ISSUE THREAD

**Issue by arugifa** [nottyo/robotframework-redislibrary#2]
First, thank you for this nice library 👍 

While using it, I was a bit intrigued by the API. In particular, the fact that we always have to pass the Redis connection to each keyword of the library. Is there any reason behind this choice?

Or could it be interesting to setup the connection during library initialization? As it is done in the [HttpLibrary](http://peritus.github.io/robotframework-httplibrary/HttpLibrary.html), [DatabaseLibrary](https://github.com/franz-see/Robotframework-Database-Library) or [MongoDBLibrary](https://github.com/iPlantCollaborativeOpenSource/Robotframework-MongoDB-Library).

**Comment by nottyo** [comment]
The Redis connection object is required to pass for every keywords because there might be some test cases that want to access more than one Redis server in one test case. So it would be more flexible if user can select which Redis server that they want to connect to.
